Repository DliDAM/backend-spring, pull requests merged in 2024-10, with the labels that each got.

#40 [fix] 채팅방 목록 조회 API 수정
  src/main/java/com/dlidam/chat/application/ChatRoomService.java
  src/main/java/com/dlidam/chat/dto/response/ChatRoomWithLastMessageResponseDTO.java
  src/main/java/com/dlidam/chat/infrastructure/webrtc/WebSocketProxy.java
  src/main/java/com/dlidam/chat/presentation/ChatRoomController.java
Labels: :wrench: fix

#41 [fix] 오디오 디코드 삭제
  src/main/java/com/dlidam/chat/application/ChatRoomService.java
  src/main/java/com/dlidam/chat/dto/response/ChatRoomWithLastMessageResponseDTO.java
  src/main/java/com/dlidam/chat/infrastructure/webrtc/WebSocketProxy.java
Labels: :wrench: fix

#42 [fix] 디코드 추가
  src/main/java/com/dlidam/chat/infrastructure/webrtc/WebSocketProxy.java
Labels: :wrench: fix

#43 [fix] 디코더 추가
  src/main/java/com/dlidam/chat/infrastructure/webrtc/WebSocketProxy.java
  src/main/java/com/dlidam/chat/presentation/ChatRoomController.java
Labels: :wrench: fix

#44 [fix] DTO 를 FastAPI에 보내도록 수정
  .DS_Store
  build.gradle
  src/main/java/com/dlidam/chat/infrastructure/webrtc/WebSocketProxy.java
  src/main/java/com/dlidam/configuration/websocket/WebSocketUtil.java
Labels: :wrench: fix

#45 [feat] 즐겨찾기 상태 변환 api 추가
  src/main/java/com/dlidam/authentication/application/AuthenticationService.java
  src/main/java/com/dlidam/authentication/presentation/AuthenticationController.java
  src/main/java/com/dlidam/authentication/presentation/dto/request/LoginTokenRequest.java
  src/main/java/com/dlidam/chat/application/ChatRoomService.java
  src/main/java/com/dlidam/chat/infrastructure/websocket/WebSocketProxy.java
  src/main/java/com/dlidam/device/application/DeviceTokenService.java
  src/main/java/com/dlidam/friend/application/FriendService.java
  src/main/java/com/dlidam/friend/domain/FriendList.java
  src/main/java/com/dlidam/friend/domain/repository/FriendListRepository.java
  src/main/java/com/dlidam/friend/infrastructure/persistence/FriendListRepositoryImpl.java
  src/main/java/com/dlidam/friend/infrastructure/persistence/JpaFriendListRepository.java
  src/main/java/com/dlidam/friend/presentation/FriendController.java
  src/main/java/com/dlidam/user/domain/User.java
  src/main/java/com/dlidam/user/presentation/UserController.java
Labels: :sparkles: feat, :wrench: fix

#47 [feat] 오디오 변환 추가
  .DS_Store
  src/main/java/com/dlidam/chat/infrastructure/websocket/WebSocketProxy.java
Labels: :sparkles: feat

#48 [feat] 오디오 파일 변환
  .DS_Store
  output.wav
  src/main/java/com/dlidam/chat/infrastructure/websocket/WebSocketProxy.java
  src/main/java/com/dlidam/configuration/audio/AudioConverter.java
  src/main/java/com/dlidam/configuration/ffmpeg/AudioConverter.java
  src/main/java/com/dlidam/configuration/ffmpeg/FFmpegConfig.java
  src/main/resources/application.yml
  src/main/resources/ffmpeg/ffmpeg
Labels: :sparkles: feat

#49 feat: 사용자 음성 가중치 입력 기능 추가
  src/main/java/com/dlidam/global/service/FastAPIService.java
  src/main/java/com/dlidam/user/presentation/UserController.java
Labels: :sparkles: feat
